### ISSUE TITLE
Step 3 doesn't work as expected

### ISSUE THREAD

**Issue by FarahZKhan** [heliumdatacommons/TOPMed_RNAseq_CWL#1] opened 2018-07-16 08:26 UTC
Hello, 
I am following the instructions given in the README document. Step 3 states: 
```
Decompress sample files: ./topmed-workflows/TOPMed_RNAseq_pipeline/input-examples/download_examples.sh
```
However, one particular file is not decompressed when I run this script: 
```
https://github.com/heliumdatacommons/cwl_workflows/blob/master/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12.tar.gz
```
For this particular file I get the following error: 
```
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```
Can you please look into this? 
Thanks

P.S. if I try to wget it, this happens: 
```
wget https://beta.commonsshare.org/django_irods/download/68ce40f872cd48db8b3adb3b334242af/data/star-index-chr12.tar.gz
--2018-07-16 18:37:33--  https://beta.commonsshare.org/django_irods/download/68ce40f872cd48db8b3adb3b334242af/data/star-index-chr12.tar.gz
Resolving beta.commonsshare.org (beta.commonsshare.org)... 152.54.3.49
Connecting to beta.commonsshare.org (beta.commonsshare.org)|152.54.3.49|:443... connected.
HTTP request sent, awaiting response... 403 FORBIDDEN
2018-07-16 18:37:34 ERROR 403: FORBIDDEN.
```

**Comment by cmball1** [comment] 2018-07-16 14:16
@FarahZKhan You need to have [Git LFS](https://git-lfs.github.com/) installed. The file is in GitHub [here](https://github.com/heliumdatacommons/cwl_workflows/blob/master/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12.tar.gz). Once Git LFS is installed, you should be able to just `git pull` and download the file. 

commonsshare.org doesn't allow `wget` in files larger than 1 GB, which is why I needed to use Git LFS. The Star index is just large enough to not have a good way to distribute it. 

I don't think you can `wget` the file directly from GitHub.

**Comment by FarahZKhan** [comment] 2018-07-16 14:45
Thanks for getting back to me @cmball1. 
Another issue popped up when the workflow is executed using the command: 
```
cwltool topmed-workflows/TOPMed_RNAseq_pipeline/rnaseq_pipeline_fastq.cwl topmed-workflows/TOPMed_RNAseq_pipeline/input-examples/Dockstore.json 
```
Following is snippet of error log: 
```
[step run_star] start
[job run_star] /private/tmp/docker_tmpgnafat4r$ docker \
    run \
    -i \
    --volume=/private/tmp/docker_tmpgnafat4r:/private/var/spool/cwl:rw \
    --volume=/private/var/folders/bs/8fyl2nt50252htp1d2ct1rd1g51vtc/T/tmpioci3kk2:/tmp:rw \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz:/private/var/lib/cwl/stga8b82e3b-5032-43e9-b1bc-e879d35e5dc7/LC_C13_cRNA_sequence_R1_sub.fastq.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz:/private/var/lib/cwl/stg3410bcf1-1c13-4eb6-bb23-f301d0fe9696/LC_C13_cRNA_sequence_R2_sub.fastq.gz:ro \
    --volume=/Users/farahk/Documents/conformanceTest-CWLProv/cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12:/private/var/lib/cwl/stg8d4fe794-3680-4f03-9d2d-d729080417a5/star_chr12:ro \
    --workdir=/private/var/spool/cwl \
    --read-only=true \
    --user=1582362444:1793139257 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/private/var/spool/cwl \
    heliumdatacommons/topmed-rnaseq:latest \
    /src/run_STAR.py \
    /private/var/lib/cwl/stg8d4fe794-3680-4f03-9d2d-d729080417a5/star_chr12 \
    /private/var/lib/cwl/stga8b82e3b-5032-43e9-b1bc-e879d35e5dc7/LC_C13_cRNA_sequence_R1_sub.fastq.gz \
    /private/var/lib/cwl/stg3410bcf1-1c13-4eb6-bb23-f301d0fe9696/LC_C13_cRNA_sequence_R2_sub.fastq.gz \
    LC_C13_cRNA \
    --threads \
    4
Jul 16 14:41:47 ..... started STAR run
Jul 16 14:41:47 ..... loading genome
Jul 16 14:41:57 ..... started 1st pass mapping
Traceback (most recent call last):
  File "/src/run_STAR.py", line 92, in <module>
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'STAR --runMode alignReads --runThreadN 4 --genomeDir /private/var/lib/cwl/stg8d4fe794-3680-4f03-9d2d-d729080417a5/star_chr12 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /private/var/lib/cwl/stga8b82e3b-5032-43e9-b1bc-e879d35e5dc7/LC_C13_cRNA_sequence_R1_sub.fastq.gz /private/var/lib/cwl/stg3410bcf1-1c13-4eb6-bb23-f301d0fe9696/LC_C13_cRNA_sequence_R2_sub.fastq.gz --readFilesCommand zcat --outFileNamePrefix ./LC_C13_cRNA. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1' returned non-zero exit status -9
[job run_star] Job error:
Error collecting output for parameter 'bam_file':
topmed-workflows/TOPMed_RNAseq_pipeline/star.cwl:49:7: Did not find output file with glob pattern: '['*.Aligned.sortedByCoord.out.bam']'
```

Any help will be much appreciated. Thanks a lot.

**Comment by cmball1** [comment] 2018-07-16 15:38
@FarahZKhan  From the base of the repo, if you `$ ls topmed-workflows/TOPMed_RNAseq_pipeline/test-data/`, do you have the following:
```
star_chr12/
sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz
sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz
```

The `star_chr12/` is the untarred contents of `star_chr12.tar.gz`.

**Comment by cmball1** [comment] 2018-07-16 15:39
Also, this should be the version of the docker container it runs:
```
$ docker pull heliumdatacommons/topmed-rnaseq:latest
latest: Pulling from heliumdatacommons/topmed-rnaseq
Digest: sha256:09df30bef7a245b624e5826bd669d522ff44deb570c262a2e3d41a772d65b466
```

**Comment by FarahZKhan** [comment] 2018-07-16 15:41
Hi @cmball1 Yes, I have this data in the designated directories. 
```
(testing) farahk:~/Documents/conformanceTest-CWLProv/cwl_workflows$ ls topmed-workflows/TOPMed_RNAseq_pipeline/test-data
reference-files/        reference-files.tar.gz  rsem_reference/         rsem_reference.tar.gz   sample/                 star_chr12/             star_chr12.tar.gz
(testing) farahk:~/Documents/conformanceTest-CWLProv/cwl_workflows$ ls topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/
LC_C13_cRNA_sequence_R1_sub.fastq.gz  LC_C13_cRNA_sequence_R2_sub.fastq.gz
```

**Comment by FarahZKhan** [comment] 2018-07-16 15:42
```
(testing) farahk:~/Documents/conformanceTest-CWLProv/cwl_workflows$ docker pull heliumdatacommons/topmed-rnaseq:latest
latest: Pulling from heliumdatacommons/topmed-rnaseq
Digest: sha256:09df30bef7a245b624e5826bd669d522ff44deb570c262a2e3d41a772d65b466
Status: Image is up to date for heliumdatacommons/topmed-rnaseq:latest
```

**Comment by cmball1** [comment] 2018-07-16 16:05
@FarahZKhan I'm not sure why it's not working. It executes properly on my local machine. The version I have is `cwltool==1.0.20180525185854`. 

If you bypass the CWL to run the tool, does it work?
Start Docker container:
```
docker run -t -i --volume=~/<repo-path>/cwl_workflows:/cwl_workflows:rw \
    heliumdatacommons/topmed-rnaseq:latest /bin/bash
```

Run the script in the docker container:
```
/src/run_STAR.py \
    /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12 \
    /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz \
    /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz \
    LC_C13_cRNA \
    --threads 4
```

**Comment by FarahZKhan** [comment] 2018-07-16 16:30
Following is the traceback if I run it independently: 
```
(testing) farahk:~/Documents/conformanceTest-CWLProv$ docker run -t -i --volume=/Users/farahk/Documents/conformanceTest-CWLProv/cwl_workflows:/cwl_workflows:rw heliumdatacommons/topmed-rnaseq:latest /bin/bash
root@91467d21b42e:/# /src/run_STAR.py /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12 /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz  /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz LC_C13_cRNA --threads 4 
Jul 16 16:29:12 ..... started STAR run
Jul 16 16:29:12 ..... loading genome
Jul 16 16:29:22 ..... started 1st pass mapping
Traceback (most recent call last):
  File "/src/run_STAR.py", line 92, in <module>
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'STAR --runMode alignReads --runThreadN 4 --genomeDir /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz --readFilesCommand zcat --outFileNamePrefix ./LC_C13_cRNA. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1' returned non-zero exit status -9
```

**Comment by cmball1** [comment] 2018-07-16 20:08
@FarahZKhan Does anything different happen if you run it with less threads? Something like `--threads 1`?

Are you able to run this command in the Docker container?
```
STAR --runMode alignReads --runThreadN 4 --genomeDir /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz --readFilesCommand zcat --outFileNamePrefix ./LC_C13_cRNA. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1
```

**Comment by cmball1** [comment] 2018-07-16 20:09
It seems like there is an error/issue running the `STAR` command.

**Comment by FarahZKhan** [comment] 2018-07-17 04:54
:( 
no luck. 
```
root@49b86d32c1b4:/# STAR --runMode alignReads --runThreadN 4 --genomeDir /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz --readFilesCommand zcat --outFileNamePrefix ./LC_C13_cRNA. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1
Jul 17 04:53:17 ..... started STAR run
Jul 17 04:53:17 ..... loading genome
Jul 17 04:53:29 ..... started 1st pass mapping
Killed
```
Just adding, the problem persists with both, Mac and Linux.

**Comment by cmball1** [comment] 2018-07-17 18:14
I'll look into this tonight and see if I can figure anything out. STAR might not have enough resources from Docker to run (memory and disk space).

**Comment by FarahZKhan** [comment] 2018-07-18 04:33
Thanks @cmball1, I was really interested in getting this to work as it is a good example :).

**Comment by FarahZKhan** [comment] 2018-07-19 09:16
Hi @cmball1 Any luck with this one :) ?

**Comment by cmball1** [comment] 2018-07-20 17:24
@FarahZKhan Sorry for the delay. I think I was able to reproduce the issue:

```
$ STAR --runMode alignReads --runThreadN 4 --genomeDir /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/star_chr12 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R1_sub.fastq.gz /cwl_workflows/topmed-workflows/TOPMed_RNAseq_pipeline/test-data/sample/LC_C13_cRNA_sequence_R2_sub.fastq.gz --readFilesCommand zcat --outFileNamePrefix ./LC_C13_cRNA. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1
Jul 20 17:12:20 ..... started STAR run
Jul 20 17:12:20 ..... loading genome
Jul 20 17:12:31 ..... started 1st pass mapping
Jul 20 17:14:21 ..... finished 1st pass mapping
Jul 20 17:14:22 ..... inserting junctions into the genome indices
Killed
```

It looks like it's a resource issue. I changed the Docker resource limits from 4 CPU's to 2 CPU's and 8GB Memory to 3GB Memory and the command failed.

If you run `docker info`, you should be able to find the following:
```
CPUs: 2
Total Memory: 2.934GiB
```

What are the resource limits do you have set in Docker?

On a Mac, you can change it in the UI by clicking the Docker logo in the top file bar then click "Advanced".

**Comment by cmball1** [comment] 2018-07-23 12:28
From the [STAR manual](http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STAR.posix/doc/STARmanual.pdf):
```
--runThreadN option defines the number of threads to be used for genome generation, it has
to be set to the number of available cores on the server node
```

You could try setting `--runThreadN` to 1 or 2. But this is likely a memory issue. You might be able to use a different `--genomeLoad` option described in section 8.3 to lower the memory requirement. 

If we can get the `STAR` command working, I can integrate the changes to the CWL workflow.

**Comment by FarahZKhan** [comment] 2018-07-23 12:36
Hi @cmball1 I am trying these new changes you just told me and set `runThreadN` to 2 and yes it started working :). I am running the STAR command on its own.

**Comment by cmball1** [comment] 2018-07-23 12:51
@FarahZKhan If that's working, you might be able to run the CWL workflow as is with `threads` in the `Dockstore.json` set to 2. I'd also lower the `memory` option too.

**Comment by FarahZKhan** [comment] 2018-07-24 02:09
Hi @cmball1 Thanks a lot for all your help. I have modified the json file accordingly and now it is working both on mac and windows. 
I have lowered memory to 6 and threads to 2.

**Comment by cmball1** [comment] 2018-07-24 13:39
@FarahZKhan Great. I'll go ahead and close this issue. Please let me know if you have any other trouble.

**Closed as completed by cmball1** 2018-07-24 13:39 UTC
